### ISSUE TITLE
Annotating hidpi image downscales the result after being saved

### ISSUE THREAD

**Issue by Pointedstick** [ksnip/kImageAnnotator#172] opened 2020-11-28 01:25 UTC
Upon finishing annotating, the image is reduced in resolution by a factor of 2: 4K images are reduced to 1080p, and so on. This happens with both KSnip as well as Spectacle when using the kimageannotator library.

**Comment by DamirPorobic** [comment] 2020-11-28 20:54
Isn't the saved image in Spectale larger by the screen scaling factor when screen scaling enabled? Like you take a screenshot of your desktop and open it, the saved image when opened in Gewnview can't fit on the same desktop it was taken from.

**Comment by Pointedstick** [comment] 2020-11-29 00:04
That works just fine, because Gwenview has HiDPI support and knows how to display the image at the correct scale.

**Comment by DamirPorobic** [comment] 2021-01-17 17:05
I don't think that I see the issue here. I have created a screenshot and saved it and it looks the same in ksnip and in the final image when opened in Gewnview. This was with scaling factor 1.5 
![Screenshot_20210117_175924](https://user-images.githubusercontent.com/12796236/104850274-6e3ec400-58ee-11eb-9287-3a9011f23a5b.png)

**Comment by DamirPorobic** [comment] 2021-01-17 17:09
Interesting, different behavior when scaling set to 2. I'm looking into it.

**Comment by DamirPorobic** [comment] 2021-01-17 17:35
No, Gwenview tricked me by scaling the image down. I have tested again with scaling factor 2 and cannot see any issue here.

I have tested again, here is an image taken with Spectacle (no kImageAnnoator involved), the size is 1227x901
![Screenshot_20210117_182907](https://user-images.githubusercontent.com/12796236/104850967-608b3d80-58f2-11eb-9287-5c46f2a06d29.png)

A screenshot taken of the same Window with ksnip (image processed by kImageAnnotator), has the the 1234x906
![ksnip_20210117-182758](https://user-images.githubusercontent.com/12796236/104850994-831d5680-58f2-11eb-9cd3-55c5b682e4d3.png)

**Comment by Pointedstick** [comment] 2021-02-03 22:31
I'm using Spectacle, not KSnip, so maybe Spectacle code may be to blame. Here's a set of examples.

![Before, hidpi](https://user-images.githubusercontent.com/1097249/106817798-9b041280-6634-11eb-9c4f-2167a8d5d24e.jpeg)

![After, annotated, loss of resolution](https://user-images.githubusercontent.com/1097249/106817813-a0f9f380-6634-11eb-831a-16dab3fbf17d.jpeg)

The annotated image has the same resolution, but it suffers from a noticeable loss of detail. It looks like a low DPI image was upscaled to the high DPI size.

I'm willing to believe that this is Spectacle's fault if KSnip does the right thing. 200% scale BTW.

**Comment by alex1701c** [comment] 2021-02-08 08:47
@DamirPorobic I would really appreciate if you could make a bugfix release containing this fix :slightly_smiling_face:

**Comment by DamirPorobic** [comment] 2021-02-08 08:52
I was not able to reproduce the issue so far, the initial report was about different sizes, that's what I looked for but that doesn't seem to be the issue. I'll have a look at loss of details issue, haven't looked for that yet.

**Comment by DamirPorobic** [comment] 2021-02-08 19:25
@alex1701c forgot to ask, you're seeing this issue as lose of quality after annotating or something else?

**Comment by DamirPorobic** [comment] 2021-02-08 20:18
Ok, I was able to reproduce this quality lose. I'm looking into it.

**Comment by DamirPorobic** [comment] 2021-02-08 20:50
I was able to reproduce and fix this issue in ksnip by adding following line to main before creating the QApplication:

`QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);`

Maybe spectacle needs such setting too?

You can test ksnip latest to verify if the issue is fixed.

**Comment by Pointedstick** [comment] 2021-02-08 21:34
Hmm, that doesn't seem to fix it in Spectacle. :/ Maybe there's some other bug in Spectacle.

**Comment by DamirPorobic** [comment] 2021-02-08 21:38
You setting it before creating the QApplication? 

![image](https://user-images.githubusercontent.com/12796236/107284490-34309000-6a5e-11eb-8f0c-a1cdd1f6f182.png)

Can you double check if you get the issue with ksnip still?

**Comment by Pointedstick** [comment] 2021-02-08 22:23
> You setting it before creating the QApplication?

Yup.

Will check with ksnip.

**Comment by DamirPorobic** [comment] 2021-03-21 10:44
@Pointedstick I have pushed a fix that might have an effect on this issue. Can you test again with latest kImageAnnotator?

**Comment by Pointedstick** [comment] 2021-03-21 11:40
Thanks!

It seems to help for the case where I'm annotating a small screenshot, but when I take a full screen screenshot (at 3840x2160), the problem re-appears. It seems to only be conditional based on the size of the image at this point. Odd.

**Comment by DamirPorobic** [comment] 2021-03-21 13:20
That is with Spectacle? I've just tried a full screen screenshot with ksnip and the fix and it looks ok.

Can you check following two use cases:
1. Take a full screen screenshot and annotate.
2. Select a rectangle that covers the full screen and annotate.

Might be size related or related to the way the screenshot is taken. In ksnip there is a difference, might be the case in Spectacle too.

**Comment by Pointedstick** [comment] 2021-04-16 18:53
In the past I could see the difference as well, but I am no longer able to reproduce this under any circumstances! Hooray?

**Comment by DamirPorobic** [comment] 2021-04-17 07:37
I think it is a Hooray :)

**Closed by DamirPorobic** 2021-04-17 07:37 UTC
Labels: enhancement
