### ISSUE TITLE
Zoom in-out tool

### ISSUE THREAD

**Issue by MurzNN** [ksnip/kImageAnnotator#120] opened 2020-06-22 12:07 UTC
Will be good to have zoom in-out actions (only screen zoom, without resize image) for image annotator (and "Reset zoom" action), this is useful especially for screenshots from 4k screens. Is this hard to implement?

**Comment by DamirPorobic** [comment] 2020-06-22 14:36
Should be doable though I have no idea how complex that would be. We can set a scale factor when painting items but that tends to be blurry, maybe we need to look for an alternative. But painter scaling probably be my first starting point.

**Comment by DamirPorobic** [comment] 2020-06-22 14:38
This is also a duplicate of #123 which was opened before and already got some thumbs up.

**Closed by DamirPorobic** 2020-06-22 14:38 UTC
Labels: feature request
