### ISSUE TITLE
Cropping only works on one image, even if there are others

### ISSUE THREAD

**Issue by fabianski7** [ksnip/kImageAnnotator#249] opened 2021-07-04 15:29 UTC
To reproduce:

1. Take two screenshots and paste into each other (CTRL+Shift+V)
2. Use the cutting tool

It is only possible to crop the first image, not both as if they were a single image

**Comment by DamirPorobic** [comment] 2021-07-04 16:55
Yeah, because the pasted image is an annotation item that you can move around, like for example an arrow. Cropping only affects the background image.

**Comment by DamirPorobic** [comment] 2022-01-08 08:50
I'm closing this issue as it's working as designed.

**Closed by DamirPorobic** 2022-01-08 08:50 UTC
Labels: question
