### ISSUE TITLE
Allow scaling stickers per setting

### ISSUE THREAD

**Issue by itsnotsaved** [ksnip/kImageAnnotator#285] opened 2022-03-21 07:51 UTC
**Is your feature request related to a problem? Please describe.**
It's possible to scale numbers using font size box and [this way](https://github.com/ksnip/ksnip/issues/836#issuecomment-1066817898) but stickers only can scale using 2nd method then,

1. if need to make sticker large or small, we need to do it carefully otherwise width and height mismatch then it waste time
2. we cannot keep same size (e.g. if i need multiple tick marks) for next stickers, when add new sticker then it appear with default size

**Describe the solution you'd like**
Add resize box (font size box) for this too.

**Comment by itsnotsaved** [comment] 2022-03-23 07:31
>I think you are mixing two things here. You can only scale items, so the whole circle of the number item or the whole sticker. The Font size dictates only the size of the font used for the number, you can scale the number item but the number still being small.

I understand this part. I'm trying to explain something different.
1. Currently when i want to scale a sticker then i need to drag/pull it to be smaller or large but i need to do that carefully to avoid  mismatch width and height (sorry, i dont know the technical word). i don't want to happen this e.g. current size 2mm (height) 4mm (width) and new size 4.3mm (height) 9mm (width)

If has resize box as font size box then i can resize stickers quickly and properly (-2x, -1x, 0, +1x, +2x) etc. 

2. If i need to add same size multiple tick mark stickers, ksnip doesn't keep remember the last scaled size for next sticker and it's not easy to scale again using hand for match to previous sticker size

**Comment by DamirPorobic** [comment] 2022-03-23 07:59
I do get your issue it's just not simply fixed by adding a size picker. The issue is that we have not fixed based, you have no value that is shared between the stickers but the multiplication that you mentioned there could be a way to go, I would say we go with 100% being the default and you can then increase or decrease the size. Still need to think about the implication of combining the box resizing and the settings resizing but it could be doable.

**Comment by DamirPorobic** [comment] 2022-04-03 10:17
Implemented

**Closed by DamirPorobic** 2022-04-03 10:17 UTC
Labels: feature_request
