### ISSUE TITLE
Deleting item outside image doesn't decrease canvas size

### ISSUE THREAD

**Issue by MurzNN** [ksnip/kImageAnnotator#164] opened 2020-11-16 08:30 UTC
When we have capture with mouse cursor, and try to crop it, cursor was stay in image and extend the cropping area, even when we save image. And even if we delete it manually afterwards, the saved image will still have more area, than cropped.

**Comment by DamirPorobic** [comment] 2020-11-16 08:36
That the cursor is not deleted when you crop the image is expected behavior, because it's an annotation item. The only issue here is that last sentence which should not be like that.

**Comment by DamirPorobic** [comment] 2021-01-02 14:38
I can reproduce this issue. Deleting an item does not restore the canvas but undoing it does.

**Comment by DamirPorobic** [comment] 2021-01-03 18:36
This is fixed in version `1.9.0`

**Closed by DamirPorobic** 2021-01-03 18:36 UTC
Labels: bug
