### ISSUE TITLE
Text suggestion: Selection using keyboard shortcuts (ctrl+A; shift+arrows; shift+end; shift+home)

### ISSUE THREAD

**Issue by carloscadux** [ksnip/kImageAnnotator#274] opened 2022-01-07 16:19 UTC
Hi,
 
I'm using ksnip build 1-1ccc20b on Windows 11.
 
Currently, it seems there is no effect when pressing common keystrokes for text selection, like:
`ctrl+A`
`shift+arrows`
`shift+end`
`shift+home`
 
I'd like to suggest the text selection by using those keyboard shortcuts. 
 
The suggestion is illustrated in this screen-recording (https://tinyurl.com/y6yuss54).
 
Thanks,
Carlos

**Comment by DamirPorobic** [comment] 2022-01-07 21:12
I think duplicate of https://github.com/ksnip/kImageAnnotator/issues/198, maybe you can add your expectation there.

**Comment by carloscadux** [comment] 2022-01-12 13:49
> I think duplicate of #198, maybe you can add your expectation there.

Thanks for letting me know. I just posted on #198.

**Comment by DamirPorobic** [comment] 2022-01-12 15:14
Closing duplicate.

**Closed by DamirPorobic** 2022-01-12 15:14 UTC
Labels: duplicate, feature request
